language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libboost-thread-dev 
      - libboost-system-dev
      - libboost-regex-dev
      - libboost-date-time-dev 
      - libboost-test-dev
 
script: ./travis.sh 

notifications:
  email:
    - cukes-devs@googlegroups.com
